openapi: 3.0.3
info:
  title: Auth API - Medine.dev
  description: ERP API - Medine.dev
  version: 1.0.0
servers:
  - url: 'http://127.0.0.1:8000/'
paths:
  /oauth/token:
    post:
      summary: Add a new pet
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Message'
      responses:
        '201':
          description: Created

components:
  schemas:
    Message:
      title: A Slack message
      type: object
      properties:
        grant_type:
          type: string
          description: Message text
          example: password
        client_id:
          type: integer
          description: Message text
          example: 2
        client_secret:
          type: string
          description: Message text
          example: N3fxaxpkVu2Q6zlFgsn3B3Dbftc87Qzz1cs36FS9
        username:
          type: string
          description: Message text
          example: fjmn2001@gmail.com
        password:
          type: string
          description: Message text
          example: password
      required:
        - grant_type
